name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - name: Checkout from GitHub
        uses: actions/checkout@master

      - name: Configure Google Cloud credentials
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/266324743316/locations/global/workloadIdentityPools/github/providers/github-oidc'
          service_account: 'github-actions@mw-lunarclient-maven-repo.iam.gserviceaccount.com'

      - name: Use JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Build
        run: ./gradlew publish
